/process/em/verbose 0
/process/had/verbose 0
# /tracking/verbose 1

/detector/gdml cms2018.gdml
/detector/field 0 0 3.8 T

# Model settings from FTFPCMS_BERT_EMM
#  - CMSEmStandardPhysics(LPM)
/process/em/applyCuts true
/process/eLoss/StepFunction 0.8 1 mm
/process/msc/RangeFactor 0.2
/process/msc/StepLimit Minimal
# Possibly a different step limit for "HcalRegion" and "HGCalRegion" in
# CMSEmStandardPhysics, to be checked.

#  - CMSHadronPhysicsFTFP_BERT(106)
/FTFP_BERT/pion 3 12 GeV
/FTFP_BERT/kaon 3 6 GeV
/FTFP_BERT/proton 3 6 GeV
/FTFP_BERT/neutron 3 6 GeV

/maxTrackTime 500 ns

# Configuration of russian roulette performed in StackingAction
/russianRoulette/gamma 0.3 5 MeV
/russianRoulette/neutron 0.1 10 MeV

/run/initialize

/deadRegion QuadRegion
/deadRegion InterimRegion

/generator/hepMCfile gg2ttbar.dat
/run/beamOn 1
